# Generated by Django 5.1.5 on 2025-01-31 14:43

import django_choices_field.fields
import ideas_app.ideas.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="title",
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="idea",
            name="visibility",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("public", "Public"),
                    ("private", "Private"),
                    ("protected", "Protected"),
                ],
                choices_enum=ideas_app.ideas.models.Idea.Visibility,
                default="protected",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="idea",
            name="text",
            field=models.CharField(max_length=255),
        ),
    ]
