# Generated by Django 5.1.5 on 2025-01-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ideas", "0002_idea_title_idea_visibility_alter_idea_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="idea",
            name="pub_date",
            field=models.DateTimeField(null=True),
        ),
    ]
